backend:
  name: github
  repo: olekszij/knowledge-base
  branch: main
  client_id: Ov23likg3BGJ4XZ69E9u
  client_secret: be3a86d2ad4da2cb603c6cd07cc9f65648ddde05

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Astro", "Decap", "Jamstack", "UI", "Other"], default: "Other"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "snippets"
    label: "Code Snippets"
    label_singular: "Snippet"
    folder: "src/content/snippets"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Astro", "Decap", "Jamstack", "UI", "Other"], default: "Other"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Language", name: "language", widget: "select", options: ["javascript", "typescript", "astro", "css", "html", "python", "rust", "go"], default: "javascript"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

editor:
  preview: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

site_url: "https://jamstack-base.netlify.app"
display_url: "https://jamstack-base.netlify.app"